combine_control_expr = true
wrap_comments = false
brace_style = "PreferSameLine"
enum_discrim_align_threshold = 20
fn_single_line = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
imports_granularity = "Module"
normalize_comments = true
reorder_impl_items = true
reorder_imports = true
struct_field_align_threshold = 20
trailing_semicolon = true
type_punctuation_density = "Compressed"
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
overflow_delimited_expr = true
normalize_doc_attributes = true
use_small_heuristics = "Default"
blank_lines_lower_bound=0
blank_lines_upper_bound=1
comment_width=120
condense_wildcard_suffixes=true
control_brace_style="AlwaysSameLine"
empty_item_single_line=true
remove_nested_parens=true
group_imports="StdExternalCrate"
where_single_line=true
